
export const LOGIN_REQUEST = 'lOGIN_REQUEST';
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';


export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const BRAND_REQUEST = 'BRAND_REQUEST';
export const VENDOR_REQUEST = 'VENDOR_REQUEST';
export const PRODUCT_CLASS_REQUEST = 'PRODUCT_CLASS_REQUEST';


export const REQUEST_INVOICES  = 'GET_INVOICES';
export const REQUEST_INVOICE = 'GET_INVOICE';
export const REQUEST_PAYMENT_MRTHOD = 'PAYMENT_METHOD_REQUEST';
export const PAYMENT_REQUEST = 'PAYMENT_REQUEST';