# Generated by Django 3.0.7 on 2020-06-17 12:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150, verbose_name='Ονομασια')),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=20)),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='Ποσότητα')),
                ('price_buy', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Αξία Αγορας')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Τιμή Πώλησης')),
                ('value_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Τιμή Έκπτωσης')),
                ('final_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Brand')),
                ('categories', models.ManyToManyField(blank=True, to='products.Category', verbose_name='Κατηγορίες')),
            ],
            options={
                'verbose_name': 'Προϊόν',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Αγαπημένο')),
                ('sku', models.CharField(blank=True, max_length=150, verbose_name='Κωδικος Τιμολογιου')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Αρχική Αξία')),
                ('discount', models.IntegerField(default=0, verbose_name='Εκπτωση')),
                ('clean_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Καθαρη Αξια')),
                ('taxes_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Αξια μετα Φορους')),
                ('added_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Επιπλεον Αξια')),
                ('final_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Τελικη Αξια')),
                ('taxes_modifier', models.CharField(choices=[('a', 13)], default='c', max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendors', to='products.Product', verbose_name='Προϊον')),
                ('vendor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.Vendor', verbose_name='Προμηθευτης')),
            ],
            options={
                'ordering': ['-is_favorite', 'product__title'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Vendor'),
        ),
    ]
