# Generated by Django 2.2 on 2020-07-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200624_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('is_service', models.BooleanField(default=False)),
                ('have_warehouse', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductClass'),
        ),
    ]
