# Generated by Django 2.2 on 2020-07-10 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200701_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Διεύθυνση'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='afm',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='ΑΦΜ'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Περιγραφή'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='doy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='fax',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Τηλέφωνο'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Τηλέφωνο'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='site',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 7, 10, 4, 55, 38, 789618, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
